language: php

php: [5.6, 7.0, hhvm]

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

branches:
  except:
    - /^bugfix\/.*$/
    - /^feature\/.*$/
    - /^optimization\/.*$/

matrix:
  fast_finish: true
  include:
    - php: '7.0'

install:
  - curl -s http://getcomposer.org/installer | php
  - composer global require "fxp/composer-asset-plugin:^1.2.0"
  - php composer.phar install --dev --no-interaction

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist

after_success:
  - travis_retry php vendor/bin/coveralls
