language: php

php: [5.6, 7.0, hhvm]

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

branches:
  except:
    - /^bugfix\/.*$/
    - /^feature\/.*$/
    - /^optimization\/.*$/

matrix:
  fast_finish: true
  include:
    - php: '7.0'

before_script:
  - travis_retry composer install --no-interaction

script: phpunit --configuration phpunit.xml --coverage-text
